#!/bin/bash

# Variables And Data
  repo_url="https://github.com/twozeroonesix/Arch-Hypr-Dotfiles"
  conf_dir=""
  Pacman_Packages=(
    hyprland
    net-tools
    alacritty
    python3
    python-pip
    base-devel
    btop
    fastfetch
    waybar
    rofi
    cliphist
    wl-clipboard
    networkmanager
    nm-connection-editor
    swaync
    swaybg
    swww
    hyprpaper
    hyprlock
    pavucontrol
    font-manager
    ttf-font-awesome
    ttf-nerd-fonts-symbols
    aria2
    unrar
    file-roller
    thunar
    tumbler
    gvfs
    git
    mousepad
    nerd-fonts)
  AUR_Packages=(
    ttf-material-design-icons
    cava
    wlogout
    waypaper-git
    python-pywal16
    librewolf-bin
    wlogout
    mpvpaper
    ffmpegthumbnailer
    hyprctl-rofi
    hyprshot
    qt6ct-kde)
# Install Packages
  pacman -Sy --needed "${Pacman_Packages[@]}"
  yay -Sy --needed "${AUR_Packages[@]}"
# Install ETC.
  
# Prepare and Make Folders 
  mkdir -p $HOME/HOME-BACKUP # $HOME Backup Folder
  mkdir -p $HOME/Wallpapers # Wallpapers Folder
  # Make Folders For Dotfiles configs
    mkdir -p $HOME/.config/hypr/conf
    mkdir -p $HOME/.config/hypr/scripts
    mkdir -p $HOME/.config/kitty/scripts
    mkdir -p $HOME/.config/waybar/scripts
# Download a Config Dotfiles
  # Fetch Fles Function
    fetch()
    [local="$1" local="$2" local="$3" wget "${repo}/${fp}" -O "$dp"]
  # Fetch Files
    # Hypr Folder
      fetch "$repo_url" "Dotfiles/main/hypr/hyprland.conf" "$HOME/.config/hypr/hyprland.conf" 
      fetch "$repo_url" "Dotfiles/main/hypr/hyplock.conf" "$HOME/.config/hypr/hyprlock.conf"
      # Conf Floder
        fetch "$repo_url" "Dotfiles/main/hypr/conf/animations.conf" "$HOME/.config/hypr/conf/animations.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/autostart.conf" "$HOME/.config/hypr/conf/autostart.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/binds.conf" "$HOME/.config/hypr/conf/binds.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/colors.conf" "$HOME/.config/hypr/conf/colors.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/decorations.conf" "$HOME/.config/hypr/conf/decorations.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/env.conf" "$HOME/.config/hypr/conf/env.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/general.conf" "$HOME/.config/hypr/conf/general.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/input.conf" "$HOME/.config/hypr/conf/input.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/layerrules.conf" "$HOME/.config/hypr/conf/layerrules.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/misc.conf" "$HOME/.config/hypr/conf/misc.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/programs.conf" "$HOME/.config/hypr/conf/programs.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/windowrules.conf" "$HOME/.config/hypr/conf/windowrules.conf"
        fetch "$repo_url" "Dotfiles/main/hypr/conf/workspacerules.conf" "$HOME/.config/hypr/conf/workspacerules.conf"
      # Scripts Folder
        fetch "$repo_url" "Dotfiles/main/hypr/scripts/hyprmode-v2.sh" "$HOME/.config/scripts/hyprmode-v2.sh"
        fetch "$repo_url" "Dotfiles/main/hypr/scripts/rofi-wallpaper.sh" "$HOME/.config/scripts/rofi-wallpaper.sh"
        fetch "$repo_url" "Dotfiles/main/hypr/scripts/show-pywal-colors.sh" "$HOME/.config/scripts/show-pywal-colors.sh"
        fetch "$repo_url" "Dotfiles/main/hypr/scripts/waybarmode.sh" "$HOME/.config/scripts/waybarmode.sh"
    # Kitty Folder
      fetch "$repo_url" "Dotfiles/main/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"
      # Scripts Folder
        fetch "$repo_url" "Dotfiles/main/kitty/scripts/dark-pywal.sh" "$HOME/.config/kitty/scripts/dark-pywal.sh"
        fetch "$repo_url" "Dotfiles/main/kitty/scripts/light-pywal.sh" "$HOME/.config/kitty/scripts/light-pywal.sh"
        fetch "$repo_url" "Dotfiles/main/kitty/scripts/dark-pywal2.sh" "$HOME/.config/kitty/scripts/dark-pywal2.sh"
        fetch "$repo_url" "Dotfiles/main/kitty/scripts/light-pywal2в.sh" "$HOME/.config/kitty/scripts/light-pywal2.sh"
    # Waybar Folder
      fetch "$repo_url" "Dotfiles/main/waybar/config.jsonc" "$HOME/.config/waybar/config.jsonc"
      fetch "$repo_url" "Dotfiles/main/waybar/style.css" "$HOME/.config/waybar/style.css"
      # Scripts Folder
        fetch "$repo_url" "Dotfiles/main/waybar/scripts/weather.py" "$HOME/.config/waybar/scripts/weather.py"
        fetch "$repo_url" "Dotfiles/main/waybar/scripts/cavabar.sh" "$HOME/.config/waybar/scripts/cavabar.sh"
      # Styles Folder
        fetch "$repo_url" "Dotfiles/main/waybar/styles/s-corner-dark.css" "$HOME/.config/waybar/styles/s-corner-dark.css"
        fetch "$repo_url" "Dotfiles/main/waybar/styles/s-corner-dark2.css" "$HOME/.config/waybar/styles/s-corner-dark2.css"
        fetch "$repo_url" "Dotfiles/main/waybar/styles/s-corner-light.css" "$HOME/.config/waybar/styles/s-corner-light.css"
        fetch "$repo_url" "Dotfiles/main/waybar/styles/s-corner-light2.css" "$HOME/.config/waybar/styles/s-corner-light2.css"
        fetch "$repo_url" "Dotfiles/main/waybar/styles/s-corner-dark.css" "$HOME/.config/waybar/styles/walbar-dark.css"
        fetch "$repo_url" "Dotfiles/main/waybar/styles/s-corner-dark2.css" "$HOME/.config/waybar/styles/walbar-light.css"
        fetch "$repo_url" "Dotfiles/main/waybar/styles/s-corner-dark.css" "$HOME/.config/waybar/styles/dark.css"
        fetch "$repo_url" "Dotfiles/main/waybar/styles/s-corner-dark2.css" "$HOME/.config/waybar/styles/light.css"
        
