# Shell variables
# Generated by 'wal'
wallpaper="/home/unner/Wallpapers/trippy-purple.png"

# Special
background='#0a0a11'
foreground='#c1c1c3'
cursor='#c1c1c3'

# Colors
color0='#0a0a11'
color1='#525569'
color2='#61647A'
color3='#6F738A'
color4='#7B7DA1'
color5='#7E819B'
color6='#8F8EAC'
color7='#c1c1c3'
color8='#57576b'
color9='#525569'
color10='#61647A'
color11='#6F738A'
color12='#7B7DA1'
color13='#7E819B'
color14='#8F8EAC'
color15='#c1c1c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
