# Shell variables
# Generated by 'wal'
wallpaper="/home/unner/Wallpapers/ellen-joe.jpg"

# Special
background='#1c1414'
foreground='#c6c4c4'
cursor='#c6c4c4'

# Colors
color0='#1c1414'
color1='#E74675'
color2='#B06B8A'
color3='#EE5D8E'
color4='#988382'
color5='#A89698'
color6='#D39BA9'
color7='#c6c4c4'
color8='#725e5e'
color9='#E74675'
color10='#B06B8A'
color11='#EE5D8E'
color12='#988382'
color13='#A89698'
color14='#D39BA9'
color15='#c6c4c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
