--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/unner/Wallpapers/ellen-joe.jpg"

-- Special
background="#1c1414"
foreground="#c6c4c4"
cursor="#c6c4c4"

-- Colors
color0="#1c1414"
color1="#E74675"
color2="#B06B8A"
color3="#EE5D8E"
color4="#988382"
color5="#A89698"
color6="#D39BA9"
color7="#c6c4c4"
color8="#725e5e"
color9="#E74675"
color10="#B06B8A"
color11="#EE5D8E"
color12="#988382"
color13="#A89698"
color14="#D39BA9"
color15="#c6c4c4"
