[colors.primary]
background = "#0a0a11"
foreground = "#c1c1c3"

[colors.cursor]
text = "#0a0a11"
cursor = "#c1c1c3"

[colors.vi_mode_cursor]
text = "#0a0a11"
cursor = "#c1c1c3"

[colors.search.matches]
foreground = "#0a0a11"
background = "#c1c1c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#57576b"
background = "#c1c1c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a0a11"
red = "#525569"
green = "#61647A"
yellow = "#6F738A"
blue = "#7B7DA1"
magenta = "#7E819B"
cyan = "#8F8EAC"
white = "#c1c1c3"

[colors.bright]
black = "#57576b"
red = "#525569"
green = "#61647A"
yellow = "#6F738A"
blue = "#7B7DA1"
magenta = "#7E819B"
cyan = "#8F8EAC"
white = "#c1c1c3"

[colors.dim]
black = "#c1c1c3"
red = "#525569"
green = "#7E819B"
yellow = "#6F738A"
blue = "#7B7DA1"
magenta = "#61647A"
cyan = "#8F8EAC"
white = "#57576b"

