[colors.primary]
background = "#1c1414"
foreground = "#c6c4c4"

[colors.cursor]
text = "#1c1414"
cursor = "#c6c4c4"

[colors.vi_mode_cursor]
text = "#1c1414"
cursor = "#c6c4c4"

[colors.search.matches]
foreground = "#1c1414"
background = "#c6c4c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#725e5e"
background = "#c6c4c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#1c1414"
red = "#E74675"
green = "#B06B8A"
yellow = "#EE5D8E"
blue = "#988382"
magenta = "#A89698"
cyan = "#D39BA9"
white = "#c6c4c4"

[colors.bright]
black = "#725e5e"
red = "#E74675"
green = "#B06B8A"
yellow = "#EE5D8E"
blue = "#988382"
magenta = "#A89698"
cyan = "#D39BA9"
white = "#c6c4c4"

[colors.dim]
black = "#c6c4c4"
red = "#E74675"
green = "#A89698"
yellow = "#EE5D8E"
blue = "#988382"
magenta = "#B06B8A"
cyan = "#D39BA9"
white = "#725e5e"

