[general]
	import = ["/home/unner/.cache/wal/colors-alacritty.toml"]
[env]
	#live_config_reload = true
[terminal]
	shell = { program = "/bin/zsh" }
[window]
	title = "Alacritty"
	padding = { x = 20, y = 20 }
	dynamic_padding = true
	blur = true
	opacity = 0.7
[font]
	glyph_offset = { x = 0, y = 0 }
	normal = { family = "SF Mono", style = "Regular" }
	size = 7.5
